services:
  # Backend
  - type: web
    name: planwizz-backend
    plan: free
    runtime: docker
    dockerContext: Springboot
    dockerfilePath: Springboot/Dockerfile

  # Frontend
  - type: web
    name: planwizz-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
