services:
  # Backend
  - type: web
    name: planwizz-backend
    plan: free
    runtime: docker
    dockerContext: Springboot
    dockerfilePath: Dockerfile

  # Frontend
  - type: web
    name: planwizz-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: planwizz-backend
          property: host
